name: flutter_fft
description: A fixed local version of flutter_fft.
version: 1.0.2+6

flutter:
  plugin:
    platforms:
      android:
        package: com.slins.flutterfft
        pluginClass: FlutterFftPlugin

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^11.4.0

