name: vibedash_flutter
description: Minimal working Flutter audio visualizer app
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_audio_capture: ^1.1.11
  permission_handler: ^12.0.0+1
  flutter_fft:
    path: ./flutter_fft_fixed

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
